# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"

  #config.vm.network "forwarded_port", guest: 514, host:5140

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 * 2
    vb.cpus = 2
  end

  config.vm.provision :shell do |s|
    s.path = 'vagrant-provisioner.sh'
    s.args = []
  end
end
